name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # 每天凌晨更新一次
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }} # 需要你去 Settings 生成一个 classic token
          user: kkkkarry
          template: classic
          base: header, community, repositories, metadata
          config_timezone: Asia/Shanghai
